// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CANopenUiTest

#include "../ui.h"

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSplash = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_LabelSplash, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSplash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSplash, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSplash, "CANopenNode");
    lv_obj_add_flag(ui_LabelSplash, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSplash, lv_color_hex(0xFB051B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSplash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSplash, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}
