// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CANopenUiTest

#include "ui.h"
#include "esp_log.h"

void BtnConnectHandler(lv_event_t *e)
{
	// Your code here
	ESP_LOGI("UI", "Connect Button clicked.");
}